### PR TITLE
Reflect MUI changes regarding Date and Time pickers moved to MUI X from lab

### LINKED ISSUE #324: Reflect MUI changes regarding Date and Time pickers moved to MUI X from lab
## Summary 💡

`MUI` moved Date and Time pickers from `lab` to `MUI X`. Most of the components remains MIT and are accessible for free in `@mui/x-date-pickers`. This means however that they will be removed from `@mui/lab`. The migration should be pretty easy based on the [guide](https://mui.com/x/react-date-pickers/migration-lab/).

## Motivation 🔦

In my opinion `formik-mui` should reflect `MUI` changes. Currently if you try to mix the the `formik-mui-lab` Date pickers with the `@mui/x-date-pickers/LocalizationProvider` it will throw an error which makes it hard to have an up to date version of `MUI`.

### PR DESCRIPTION
**Pull request by KOliver94**
Closes #324

### CODE REVIEW

**Review by maiis — APPROVED** [review]

**Comment by cliedeman** [comment]
Thanks @KOliver94 going to start reviewing this today

**Comment by KOliver94** [comment]
Hi @cliedeman,

Have you managed to review it? Let me know if you need any change.

Thanks!

**Comment by ramspeedy** [comment]
Gentle bump on this. @cliedeman

**Comment by chrishawn** [comment]
waiting on this for an upgrade too

**Comment by KOliver94** [comment]
Hi @cliedeman,

This PR is open for more than 1.5 months. I would like to help to keep this package maintained so can you give some feedback if any change is needed or merge it?

Thanks!

**Comment by cliedeman** [comment]
Sorry for the delay. This is released now

**Pull request merged**
